# Pre-commit configuration.
# https://pre-commit.com

# pre-commit install
# pre-commit run --all-files

repos:
  # Fix some errors with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-zero ]
        name: "ruff: fixing"
      - id: ruff-format
        name: "ruff: formatting"

  # Lint Python files with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        name: "ruff: linting"

  # Check other files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
